### ISSUE TITLE
Readme missing

### ISSUE THREAD

**Issue by jhamfler** [agross/watchr#1]
It is not obvious to me how to set it up. Please provide a readme sometime so I don't have to dig :)

**Comment by agross** [comment]
I didn't expect anyone else to use it ;-)

To compile yourself:

1. Install Ruby + SDK
1. `gem install bundler`
1. `bundle install`
1. `bundle exec rake`
1. `build/bin` will contain binaries for the web, console and WinForms
1. I deployed to http://watch.grossweber.com/

Some notes:
* You need your shell to log ANSI sequences to a file. I use [screen w/ mintty](https://github.com/agross/dotfiles/blob/master/mintty/zprofile.zsh) on Windows and [iTerm](https://stackoverflow.com/a/35798807/149264) on macOS
* The glob for the logs need to go in the `app.config` files for the console and WinForms apps, as these are templated files you can change the defaults in [`config/default.yaml`](https://github.com/agross/watchr/blob/master/config/default.yaml#L11;L16)
* The same applies to the web URL

**Comment by agross** [comment]
To save you from compiling, here are the latest artifacts:

1. [Log in as Guest](https://build.home.therightstuff.de/login.html) (bottom right)
1. [Artifacts](https://build.home.therightstuff.de/viewLog.html?buildId=234145&tab=artifacts&buildTypeId=GW_Watchr_2Package), configured for my production environment

**Comment by agross** [comment]
Readme was added.
